name: Deploy Rust Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          override-path: true

      - name: Build
        run: cargo build --release

      - name: Create artifact
        run: |
          mkdir -p output
          cp target/release/your_binary_name output/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rust-binary-${{ matrix.os }}
          path: output/